"""added td value to spools.

Revision ID: 4c23182640c8
Revises: 92793c8a937c
Create Date: 2023-12-29 20:36:13.771425
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4c23182640c8'
down_revision = '92793c8a937c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spool', sa.Column('td_value', sa.Float(), nullable=True, comment='Td value of the filament'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spool', 'td_value')
    # ### end Alembic commands ###
