"""Added spool prices.

Revision ID: b82cd9e2aa6f
Revises: 92793c8a937c
Create Date: 2023-12-30 08:39:48.430846
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b82cd9e2aa6f"
down_revision = "92793c8a937c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spool", sa.Column("price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spool", "price")
    # ### end Alembic commands ###
