"""multi_colors.

Revision ID: 415a8f855e14
Revises: 395d560284b3
Create Date: 2024-05-28 18:46:12.935449
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "415a8f855e14"
down_revision = "395d560284b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filament", sa.Column("multi_color_hexes", sa.String(length=128), nullable=True))
    op.add_column("filament", sa.Column("multi_color_direction", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filament", "multi_color_direction")
    op.drop_column("filament", "multi_color_hexes")
    # ### end Alembic commands ###
