"""vendor empty spool weight.

Revision ID: 5f069e51bd89
Revises: 304a32906234
Create Date: 2024-03-26 15:07:18.366290
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5f069e51bd89"
down_revision = "304a32906234"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendor",
        sa.Column("empty_spool_weight", sa.Float(), nullable=True, comment="The weight of an empty spool."),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendor", "empty_spool_weight")
    # ### end Alembic commands ###
