"""Added external ID.

Revision ID: 395d560284b3
Revises: 5f069e51bd89
Create Date: 2024-05-12 19:30:17.261396
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "395d560284b3"
down_revision = "5f069e51bd89"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filament", sa.Column("external_id", sa.String(length=256), nullable=True))
    op.add_column("vendor", sa.Column("external_id", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendor", "external_id")
    op.drop_column("filament", "external_id")
    # ### end Alembic commands ###
