"""add dried and last_dried to spool.

Revision ID: d722b31ab635
Revises: 415a8f855e14
Create Date: 2025-06-11 16:02:56.287606
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd722b31ab635'
down_revision = '415a8f855e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spool', sa.Column('dried', sa.JSON(), nullable=False, comment='List of ISO8601 datetime strings when this spool was dried.'))
    op.add_column('spool', sa.Column('last_dried', sa.DateTime(), nullable=True, comment='The most recent drying event (UTC).'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spool', 'last_dried')
    op.drop_column('spool', 'dried')
    # ### end Alembic commands ###
