"""Auth tables.

Revision ID: 6e496ae15523
Revises: 415a8f855e14
Create Date: 2026-07-27 20:13:56.370544
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e496ae15523"
down_revision = "415a8f855e14"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False, comment="Stored lowercased."),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column(
            "email", sa.String(length=256), nullable=True, comment="Used for OIDC matching only, never delivery."
        ),
        sa.Column("password_hash", sa.Text(), nullable=True, comment="Null for OIDC- or certificate-only accounts."),
        sa.Column(
            "level", sa.String(length=16), nullable=False, comment="read, edit or manage. See spoolman.auth.levels."
        ),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("totp_secret", sa.Text(), nullable=True, comment="Fernet-encrypted. Phase 4."),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("oidc_issuer", sa.String(length=256), nullable=True, comment="Phase 3."),
        sa.Column("oidc_subject", sa.String(length=256), nullable=True, comment="Phase 3."),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("registered", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_user_id"), "auth_user", ["id"], unique=False)
    op.create_index(op.f("ix_auth_user_username"), "auth_user", ["username"], unique=True)
    op.create_table(
        "auth_api_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False, comment="Indexes the row at lookup."),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=True),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_api_key_id"), "auth_api_key", ["id"], unique=False)
    op.create_index(op.f("ix_auth_api_key_prefix"), "auth_api_key", ["prefix"], unique=True)
    op.create_index(op.f("ix_auth_api_key_user_id"), "auth_api_key", ["user_id"], unique=False)
    op.create_table(
        "auth_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True, comment="JSON object."),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["auth_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_audit_log_date"), "auth_audit_log", ["date"], unique=False)
    op.create_index(op.f("ix_auth_audit_log_id"), "auth_audit_log", ["id"], unique=False)
    op.create_table(
        "auth_certificate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "fingerprint_sha256",
            sa.String(length=95),
            nullable=False,
            comment="Colon-separated uppercase hex, 95 chars.",
        ),
        sa.Column("subject_dn", sa.String(length=512), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_certificate_fingerprint_sha256"), "auth_certificate", ["fingerprint_sha256"], unique=True
    )
    op.create_index(op.f("ix_auth_certificate_id"), "auth_certificate", ["id"], unique=False)
    op.create_index(op.f("ix_auth_certificate_user_id"), "auth_certificate", ["user_id"], unique=False)
    op.create_table(
        "auth_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False, comment="SHA-256 hex of the token."),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("remember", sa.Boolean(), nullable=False),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_session_id"), "auth_session", ["id"], unique=False)
    op.create_index(op.f("ix_auth_session_token_hash"), "auth_session", ["token_hash"], unique=True)
    op.create_index(op.f("ix_auth_session_user_id"), "auth_session", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_session_user_id"), table_name="auth_session")
    op.drop_index(op.f("ix_auth_session_token_hash"), table_name="auth_session")
    op.drop_index(op.f("ix_auth_session_id"), table_name="auth_session")
    op.drop_table("auth_session")
    op.drop_index(op.f("ix_auth_certificate_user_id"), table_name="auth_certificate")
    op.drop_index(op.f("ix_auth_certificate_id"), table_name="auth_certificate")
    op.drop_index(op.f("ix_auth_certificate_fingerprint_sha256"), table_name="auth_certificate")
    op.drop_table("auth_certificate")
    op.drop_index(op.f("ix_auth_audit_log_id"), table_name="auth_audit_log")
    op.drop_index(op.f("ix_auth_audit_log_date"), table_name="auth_audit_log")
    op.drop_table("auth_audit_log")
    op.drop_index(op.f("ix_auth_api_key_user_id"), table_name="auth_api_key")
    op.drop_index(op.f("ix_auth_api_key_prefix"), table_name="auth_api_key")
    op.drop_index(op.f("ix_auth_api_key_id"), table_name="auth_api_key")
    op.drop_table("auth_api_key")
    op.drop_index(op.f("ix_auth_user_username"), table_name="auth_user")
    op.drop_index(op.f("ix_auth_user_id"), table_name="auth_user")
    op.drop_table("auth_user")
    # ### end Alembic commands ###
