// 3D-printable filament swatch generation. The swatch is a small card meant to
// be printed in the filament itself, carrying the same info as the printed
// labels (vendor, name, material, temperatures, id) plus a Spoolman QR code.
// The text/QR sit on a separate one-layer-thick top part, in black or white —
// whichever contrasts best with the filament color — so it can be printed with
// a filament change at the last layer or a multi-material setup.

import type { IFilament } from "../../pages/filaments/model";
import { SwatchInput } from "./layout";
import { buildSwatchLayoutForStyle, getSwatchStyle } from "./styles";
import { buildSwatch3mf } from "./threeMf";

export { pickMarkingColor } from "./color";
export type { MarkingColor } from "./color";
export { buildSwatchLayout } from "./layout";
export type { MarkRect, SwatchInput, SwatchLayout, SwatchStyleSpec, SwatchTextLine } from "./layout";
export { buildSwatchLayoutForStyle, DEFAULT_SWATCH_STYLE_KEY, getSwatchStyle, SWATCH_STYLES } from "./styles";
export type { SwatchStyle } from "./styles";
export { buildSwatch3mf, buildSwatchMeshes } from "./threeMf";

/** The filament fields the swatch needs; satisfied by IFilament and by collapsed table rows. */
export type SwatchFilamentFields = Pick<
  IFilament,
  | "id"
  | "name"
  | "material"
  | "diameter"
  | "weight"
  | "settings_extruder_temp"
  | "settings_bed_temp"
  | "article_number"
  | "color_hex"
  | "multi_color_hexes"
> & { vendor?: { name?: string } | null };

export function swatchInputFromFilament(
  filament: SwatchFilamentFields,
  options: { qrPayload: string; vendorName?: string },
): SwatchInput {
  return {
    id: filament.id,
    name: filament.name || undefined,
    vendorName: options.vendorName ?? filament.vendor?.name ?? undefined,
    material: filament.material || undefined,
    diameterMm: filament.diameter,
    weightG: filament.weight,
    extruderTempC: filament.settings_extruder_temp,
    bedTempC: filament.settings_bed_temp,
    articleNumber: filament.article_number || undefined,
    colorHexes: filament.multi_color_hexes ? filament.multi_color_hexes.split(",") : [filament.color_hex],
    qrPayload: options.qrPayload,
  };
}

/** Human-readable swatch title, used for the 3MF metadata and object name. */
export function swatchTitle(input: SwatchInput): string {
  const name = [input.vendorName, input.name].filter(Boolean).join(" ");
  return name !== "" ? name : `Filament #${input.id}`;
}

function sanitizeFilenamePart(part: string): string {
  return part.replace(/\s+/g, "_").replace(/[^A-Za-z0-9._-]/g, "");
}

export function swatchFilename(input: SwatchInput, styleKey?: string | null): string {
  const parts = [`swatch_${getSwatchStyle(styleKey).key}_${input.id}`, input.vendorName, input.name]
    .filter((part): part is string => Boolean(part))
    .map(sanitizeFilenamePart)
    .filter((part) => part !== "");
  return `${parts.join("_")}.3mf`;
}

/** Generate the downloadable 3MF for a filament, using the given (or default) swatch style. */
export function generateFilamentSwatch(
  input: SwatchInput,
  styleKey?: string | null,
): { data: Uint8Array; filename: string } {
  const layout = buildSwatchLayoutForStyle(input, styleKey);
  const data = buildSwatch3mf(layout, {
    title: `${swatchTitle(input)} swatch`,
    description:
      "Filament swatch generated by Spoolman. Print the base in the filament itself; " +
      `the ${layout.markingThicknessMm} mm "marking" part on top is meant to be printed in ${layout.markingColor} ` +
      "(add a filament change at the top layer, or assign it in a multi-material setup).",
  });
  return { data, filename: swatchFilename(input, styleKey) };
}

/** Trigger a browser download of binary data. */
export function saveBinaryFile(data: Uint8Array, filename: string, mimeType = "model/3mf"): void {
  const blob = new Blob([new Uint8Array(data)], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
