import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

export default ts.config(
	// Generated, tooling-managed, and build-output directories are not linted.
	{
		ignores: [
			'build/',
			'.svelte-kit/',
			'dist/',
			'package/',
			'src/lib/paraglide/', // auto-generated by inlang paraglide-js
			'project.inlang/', // inlang-managed
			'locales/', // Weblate-managed translation files
			'playwright-report/', // generated a11y-audit report (bundled/minified JS)
			'test-results/' // generated Playwright artifacts
		]
	},
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	prettier,
	...svelte.configs.prettier,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			// Typed as `no-undef`; TypeScript already reports undefined identifiers.
			'no-undef': 'off'
			// svelte/no-navigation-without-resolve is left ON: it is the only automated guard
			// against base-path navigation bugs, and those are invisible to anyone developing
			// at the root path. It can't see through the helpers in src/lib/library/params.ts
			// (selectHref/libraryHref/... already call resolve() from $app/paths) nor through
			// components that take an already-resolved href prop, so the files where that is
			// the case carry a file-level disable naming the reason. Never "fix" one of those
			// by wrapping the call site in resolve() — that double-applies the base path.
			// svelte/prefer-svelte-reactivity is left ON to guard against in-place mutation of
			// reactive Set/Map. The current hits are all transient computation-local collections
			// and are silenced with per-line eslint-disable comments at each site.
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	}
);
