import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

export default ts.config(
	// Generated, tooling-managed, and build-output directories are not linted.
	{
		ignores: [
			'build/',
			'.svelte-kit/',
			'dist/',
			'package/',
			'src/lib/paraglide/', // auto-generated by inlang paraglide-js
			'project.inlang/', // inlang-managed
			'locales/' // Weblate-managed translation files
		]
	},
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	prettier,
	...svelte.configs.prettier,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			// Typed as `no-undef`; TypeScript already reports undefined identifiers.
			'no-undef': 'off',
			// Base-path resolution is centralized in src/lib/library/params.ts helpers
			// (selectHref/libraryHref/etc. already call resolve() from $app/paths), and
			// generic components take a pre-resolved href prop. This rule can't see through
			// those helpers, so it only produces false positives here — and blindly wrapping
			// call sites in resolve() would double-apply the deploy base path.
			'svelte/no-navigation-without-resolve': 'off'
			// svelte/prefer-svelte-reactivity is left ON to guard against in-place mutation of
			// reactive Set/Map. The current hits are all transient computation-local collections
			// and are silenced with per-line eslint-disable comments at each site.
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	}
);
