name: Sync with Upstream

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Upstream Remote
        run: git remote add upstream https://github.com/Donkie/Spoolman

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/main  # Adjust the branch as needed

      - name: Push Changes to Fork
        run: git push origin main  # Adjust the branch as needed
